### ISSUE TITLE
Unable to delete Locations

### ISSUE THREAD

**Issue by vaibhave-olr** [KiboSoftware/kibo-sandbox-data-cli#10]
Hi,
We are getting the below issue while executing clean command: **kibo-sandbox-data clean --all**

![image](https://github.com/KiboSoftware/kibo-sandbox-data-cli/assets/102792963/996495e0-1545-423d-b909-4b1c714341b8)

I've analyzed the code, it looks like we are passing **locationCode.id** instead of **locationData.code** . Can you please check and update the code?

![image](https://github.com/KiboSoftware/kibo-sandbox-data-cli/assets/102792963/bc1756ca-bd0a-4b7a-9b01-1e634e935155)

Regards,
Vaibhav

**Comment by kibo-andycoles** [comment]
Hi Vaibhav, there is no Delete Location API, you can only disable locations by setting them to inactive.

**Comment by vaibhave-olr** [comment]
Ok. Thanks for an update Andrew.
